# Generated by Django 4.1.3 on 2022-11-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_premiumplan_superadmin_normaluser_following_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='auth_user_id',
            new_name='auth_user',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='auth_user_follower_id',
            new_name='auth_user_follower',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='auth_user_following_id',
            new_name='auth_user_following',
        ),
        migrations.RenameField(
            model_name='normaluser',
            old_name='auth_user_id',
            new_name='auth_user',
        ),
        migrations.RenameField(
            model_name='normaluser',
            old_name='premium_plan_id',
            new_name='premium_plan',
        ),
        migrations.RenameField(
            model_name='superadmin',
            old_name='auth_user_id',
            new_name='auth_user',
        ),
    ]
