# Generated by Django 4.1.3 on 2022-11-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '__first__'),
        ('users', '0004_rename_auth_user_id_artist_auth_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(to='music.album'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='premium_plan_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='premium_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.premiumplan'),
        ),
    ]
