# Generated by Django 4.1.3 on 2022-11-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_artist_albums_normaluser_premium_plan_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
