# Generated by Django 4.1.3 on 2022-12-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_artist_monthly_listeners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(null=True, to='music.album'),
        ),
    ]
